insert into Movies (Title, ReleaseDate, Genres, Director) values ('Liar, The (Valehtelija)', '2003-02-18', 'Comedy|Drama', 'Davida Epelett');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Cheaper by the Dozen 2', '2009-11-15', 'Adventure|Comedy', 'Dorice Froom');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Overnight', '2014-12-12', 'Documentary', 'Daven Sanchez');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Election (Hak se wui)', '2000-02-09', 'Crime|Drama|Thriller', 'Ailene Malkie');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Yesterday Girl (Abschied von gestern - Anita G.)', '2013-10-03', 'Comedy|Romance', 'Sheba Mitchiner');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Lovers, The (Les Amants)', '2011-03-01', 'Drama', 'Candi Yves');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('The Intruders', '2019-12-04', 'Thriller', 'Patton Digwood');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Silence Before Bach, The (Die Stille vor Bach) ', '2019-11-28', 'Musical', 'Oates Shailer');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('The Emperor''s Club', '2015-06-13', 'Drama', 'Jany Howorth');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Night Flier', '2018-09-02', 'Horror', 'Axe Filshin');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Ivory Tower', '2006-02-11', 'Documentary', 'Maria Edser');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Little Fish', '2006-08-15', 'Crime|Drama|Romance|Thriller', 'Starlene Jubert');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('The Beales of Grey Gardens', '2012-04-23', 'Documentary', 'Gawen Miranda');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Pyaar Ka Punchnama', '2018-06-27', 'Comedy|Drama|Romance', 'Mickie Smythe');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Drunken Angel (Yoidore tenshi)', '2006-06-01', 'Drama|Film-Noir', 'Caritta Iannini');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Casa de mi Padre', '2009-12-30', 'Comedy', 'Rubetta O''Curneen');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Gacy', '2005-12-24', 'Crime|Drama|Horror|Thriller', 'Sterne Uwins');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Some Guy Who Kills People', '2002-12-29', 'Comedy|Thriller', 'Henderson Rishman');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Doctor Who', '2016-10-08', 'Adventure|Sci-Fi', 'Flinn Blundin');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Celine: Through the Eyes of the World', '2014-04-01', 'Documentary', 'Jacquette Whotton');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Crimson Petal and the White, The', '2004-06-01', 'Drama|Romance', 'Cordelie Tettley');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Volga - Volga', '2012-04-25', 'Comedy|Musical', 'Donelle Cargenven');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Kino-Eye (Kinoglaz)', '2019-03-12', 'Documentary', 'Marv Coldbathe');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Cool World, The', '2011-03-05', 'Crime|Drama', 'Vail Romayne');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Cyberjack (Virtual Assassin)', '2005-10-31', 'Action|Sci-Fi', 'Willy Trudgion');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Night in Old Mexico, A', '2000-10-19', 'Drama|Western', 'Charo Faragher');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Skylab, Le', '2007-01-07', 'Comedy|Drama', 'Ilsa Wallbanks');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('You''re Next', '2023-06-19', 'Horror|Thriller', 'Betteann Dannel');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Stop Making Sense', '2018-02-06', 'Documentary|Musical', 'Walsh Bernardon');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Hot Rods to Hell', '2010-12-07', 'Action|Drama|Thriller', 'Kipp Popland');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('The Boy in the Mirror', '2005-12-26', 'Adventure|Children|Drama|Fantasy', 'Paco Iacoboni');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Wind Will Carry Us, The (Bad ma ra khahad bord)', '2023-07-18', 'Drama', 'Rafferty Dacca');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Step Up 3D', '2006-04-02', 'Drama|Romance', 'Sayres Ganniclifft');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Promise, The (Versprechen, Das)', '2000-11-07', 'Drama|Romance', 'Bertha Bridat');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Young Cassidy', '2003-04-16', 'Drama', 'Skylar Southouse');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('The Road to Glory', '2023-08-24', 'Drama|War', 'Bernelle Yushkov');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Eyes of Tammy Faye, The', '2017-01-12', 'Documentary', 'Phillida Firmin');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Mickey', '2016-06-29', 'Crime|Drama', 'Dyanne Seamer');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Faces of Death 2', '2006-11-18', 'Documentary|Horror', 'Worth Farnes');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Daniel Deronda', '2003-08-22', 'Drama|Romance', 'Husain Monkleigh');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('61*', '2021-06-17', 'Drama', 'Chrysler Anselm');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Senso', '2009-12-17', 'Drama|Romance|War', 'Franciskus Dolohunty');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Spare Parts', '2006-01-20', 'Children|Drama', 'Daryl Jelly');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Dead Hate the Living!, The', '2012-01-20', 'Comedy|Horror', 'Ross Haslen');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Kicked in the Head', '2011-12-05', 'Comedy|Drama', 'Sol Fermor');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Saw VII 3D - The Final Chapter', '2023-01-13', 'Horror|Mystery|Thriller', 'Mylo Campione');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Flesh Merchant, The (Wild and Wicked, The)', '2003-09-12', 'Drama', 'Shanda Shakesby');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Sleeping Beauty', '2013-07-06', 'Drama', 'Adora Godber');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Ride the Divide', '2008-12-15', 'Adventure|Documentary', 'Vincent Robjant');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Sitter, The', '2015-11-25', 'Comedy', 'Pierrette Edridge');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Oath, The', '2004-12-18', 'Documentary', 'Junia Schrader');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Expelled: No Intelligence Allowed', '2003-10-22', 'Documentary', 'Ailina Heathfield');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Emperor of the North (Emperor of the North Pole)', '2019-09-16', 'Action|Drama|Thriller', 'Marilee Bolsteridge');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Queen of Montreuil', '2010-11-19', 'Comedy', 'Lucina Dreakin');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('K.G. (Karate Girl)', '2013-05-02', 'Action', 'Catharine MacTerlagh');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('All Passion Spent', '2004-11-17', 'Drama', 'Maryrose Maylour');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Squeeze', '2009-08-03', 'Drama', 'Elizabet Piggins');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Morning Glory', '2020-12-17', 'Drama|Romance', 'Dorella Nequest');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Loser Takes All! (Qui perd gagne !)', '2005-01-16', 'Comedy|Mystery', 'Lani Trebilcock');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Ludwig', '2011-08-01', 'Drama', 'Archaimbaud Elbourn');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Taking Care of Business', '2015-05-16', 'Comedy', 'Pet Monahan');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Manslaughter', '2020-03-31', 'Drama', 'Malchy Croizier');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Viva Riva!', '2014-03-09', 'Drama', 'Marlyn Ratledge');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Sandor slash Ida', '2018-02-13', 'Drama|Romance', 'Elisa Szymanowicz');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Rails & Ties', '2007-05-29', 'Drama', 'Pandora Gheerhaert');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Kangaroo Jack', '2016-04-14', 'Action|Comedy', 'Dulsea Valentin');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Rite, The', '2004-06-26', 'Drama|Horror|Thriller', 'Robby Pask');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Wild Rovers', '2009-03-09', 'Western', 'Jamie Draye');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Monument Ave.', '2018-10-20', 'Action|Crime|Drama', 'Alley Lapish');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('The Year Without a Santa Claus', '2009-08-13', 'Animation|Children', 'Revkah Betteson');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Last Run', '2023-11-06', 'Action|Crime|Thriller', 'Catharina Keyes');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Blue Dahlia, The', '2021-10-19', 'Crime|Drama|Film-Noir|Mystery|Thriller', 'Norri Geraghty');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Bone Collector, The', '2011-06-28', 'Thriller', 'Cayla Spennock');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Benji ', '2013-10-02', 'Documentary', 'Evangelina Inold');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('The Case of the Lucky Legs', '2014-03-25', 'Comedy|Crime|Mystery', 'Lanie Thomason');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Final Fantasy VII: Advent Children', '2002-12-10', 'Action|Adventure|Animation|Fantasy|Sci-Fi', 'Callie Beswetherick');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Salsa', '2012-04-11', 'Musical|Romance', 'Chen Haistwell');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Spider-Man: The Ultimate Villain Showdown', '2006-01-09', 'Animation', 'Oliver Masham');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Diary for Timothy, A', '2023-09-29', 'Documentary', 'Harri Chettle');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Sin of Madelon Claudet, The', '2006-04-18', 'Drama', 'Caldwell Tatlock');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Commare secca, La (Grim Reaper, The)', '2011-01-20', 'Drama|Mystery', 'Alma Seignior');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Guilty by Suspicion', '2023-09-14', 'Drama', 'Billie Hanbury');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Kingpin', '2000-08-14', 'Comedy', 'Bunnie Yitzowitz');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Jean Gentil', '2015-12-24', 'Drama', 'Judon Jurzyk');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Leviathan', '2010-10-22', 'Horror|Sci-Fi|Thriller', 'Felipa Firmin');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Silent House', '2019-06-18', 'Horror|Thriller', 'Evonne Runcieman');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Zatoichi Challenged (Zatôichi chikemuri kaidô) (Zatôichi 17)', '2016-09-08', 'Action|Drama', 'Alvis Woltman');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('World, the Flesh and the Devil, The', '2005-09-04', 'Drama|Romance|Sci-Fi', 'Herve Georgel');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Messiah of Evil', '2004-08-14', 'Horror', 'Valina Halladey');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Perfume of the Lady in Black, The (Il profumo della signora in nero)', '2021-05-28', 'Horror|Mystery|Thriller', 'Ceciley Belliveau');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Rosario Tijeras', '2006-09-19', 'Crime|Drama|Romance', 'Charisse Burditt');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Free Samples', '2011-09-18', 'Comedy|Drama', 'Reeva Reisenstein');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Two Deaths', '2003-04-13', 'Drama', 'Joshua Adamsson');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Ice Harvest, The', '2010-10-30', 'Action|Comedy|Crime|Thriller', 'Dallas Husbands');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Animal Factory', '2016-09-16', 'Crime|Drama', 'Jennie Reboulet');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Careful', '2011-12-04', 'Comedy|Horror', 'Hunt Bushill');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Smokers Only (Vagón Fumador)', '2011-12-06', 'Drama|Romance', 'Norean Gowman');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Garden of Eden, The', '2003-04-15', 'Drama', 'Kermit Edgeley');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Endless Love', '2015-08-17', 'Drama|Romance', 'Cliff Petronis');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Killings at Outpost Zeta, The', '2012-08-30', 'Drama|Sci-Fi', 'Rae Hariot');
