insert into Movies (Title, ReleaseDate, Genres, Director) values ('Mahogany', '2023-01-21', 'dpoat0@friendfeed.com', 'Dody');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Green Dolphin Street', '2022-07-24', 'mparradye1@hud.gov', 'Margette');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('I Want You', '2013-07-30', 'srentoul2@bizjournals.com', 'Sada');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Arrow, The', '2008-11-27', 'odering3@intel.com', 'Osmund');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Arachnophobia', '2010-06-20', 'kbeves4@ibm.com', 'Katrinka');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Sweet Nothing', '2011-11-11', 'bfessler5@pinterest.com', 'Bram');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Zift', '2019-03-19', 'sjoselin6@macromedia.com', 'Sephira');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Everyone Says I Love You', '2000-04-04', 'ecorbishley7@alibaba.com', 'Emmye');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Eddie Murphy Delirious', '2012-09-06', 'sandries8@springer.com', 'Sky');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Authors Anonymous', '2014-01-10', 'ksarah9@google.ca', 'Klement');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Tillbaka till Bromma', '2009-03-30', 'jgoubliera@cornell.edu', 'Jo');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Be Cool', '2021-01-28', 'jaxcellb@nasa.gov', 'Job');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Oscar and Lucinda (a.k.a. Oscar & Lucinda)', '2014-01-20', 'hbrahamsc@redcross.org', 'Hube');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('For All Mankind', '2002-01-22', 'hwarwickd@tinypic.com', 'Hewitt');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Sin Retorno', '2010-05-05', 'ncarahere@theatlantic.com', 'Nickolai');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('First Squad: The Moment of Truth', '2012-12-19', 'aclarricoatesf@pcworld.com', 'Alice');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Captain Mike Across America (Slacker Uprising)', '2003-07-31', 'zpaolinellig@bloomberg.com', 'Zeke');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('High, Wide, and Handsome', '2011-04-18', 'kminerdoh@apple.com', 'Kenn');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('World''s Fastest Indian, The', '2008-05-28', 'ksaunierei@ow.ly', 'Korney');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Angel in Cracow (Aniol w Krakowie)', '2007-07-28', 'osmittonj@cmu.edu', 'Otis');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Man Who Knew Too Little, The', '2015-09-16', 'gsporlek@scribd.com', 'Gay');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Little Fauss and Big Halsy', '2015-01-05', 'ddunsterl@gnu.org', 'Doro');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Dhobi Ghat', '2012-11-03', 'blippm@purevolume.com', 'Breanne');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Guy Named Joe, A', '2020-09-30', 'dianellin@sitemeter.com', 'Delmor');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Batman: The Dark Knight Returns, Part 1', '2003-11-08', 'dcardiso@unc.edu', 'Darb');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Arctic Blast', '2015-07-24', 'pelnerp@plala.or.jp', 'Poppy');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Winter''s Tale', '2023-09-05', 'esparyq@artisteer.com', 'Emmaline');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Fans', '2019-11-05', 'fjaskowiczr@hugedomains.com', 'Farrah');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Fantastic Flesh: The Art of Make-Up EFX', '2011-01-01', 'csomerleds@tuttocitta.it', 'Cyril');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('One Man Band', '2013-01-08', 'terwint@deliciousdays.com', 'Teddy');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Mitchell', '2021-09-18', 'kbowenu@amazon.de', 'Kirby');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Black Stallion Returns, The', '2006-11-16', 'afordev@domainmarket.com', 'Alan');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Nickelodeon', '2010-04-25', 'wvignalw@admin.ch', 'Willamina');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Humble Pie (American Fork)', '2006-01-28', 'bstorerx@youku.com', 'Berky');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Phoenix', '2004-07-12', 'aburboroughy@sitemeter.com', 'Adrienne');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Taifu Club (Taifû kurabu)', '2001-12-16', 'mowthwaitez@japanpost.jp', 'Marcelle');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Bad Ass', '2006-04-26', 'pbrobak10@sfgate.com', 'Philipa');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Seabiscuit', '2022-03-21', 'cdelhanty11@cbc.ca', 'Carri');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Made of Honor', '2008-03-03', 'mkabsch12@gizmodo.com', 'Marijn');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('High and the Mighty, The', '2021-02-03', 'kbowdon13@foxnews.com', 'Kipp');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Hornets'' Nest', '2008-12-17', 'omolfino14@sun.com', 'Ode');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Dead Zone, The', '2013-06-16', 'mjay15@answers.com', 'Moise');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Assassin Next Door, The (Kirot)', '2019-11-29', 'mdiggell16@apple.com', 'Melantha');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Deadline', '2008-06-26', 'fjudgkins17@usa.gov', 'Farah');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Punksters & Youngsters (Punk - Tauti joka ei tapa)', '2008-06-08', 'glibbie18@symantec.com', 'Gusella');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Medicine Man', '2005-08-10', 'hjuszczyk19@mayoclinic.com', 'Happy');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Voyage to the Prehistoric Planet', '2011-05-10', 'cambrogioni1a@squidoo.com', 'Calla');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Detonator, The', '2008-10-16', 'bwrates1b@auda.org.au', 'Blinni');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Follow Me, Boys!', '2012-01-05', 'crissen1c@forbes.com', 'Cammy');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Zaza', '2005-10-25', 'mburlay1d@flavors.me', 'Marketa');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Suicide Manual (Jisatsu manyaru)', '2015-01-30', 'bwickmann1e@zdnet.com', 'Bearnard');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Sixth of the World, A (Shestaya chast mira)', '2018-12-03', 'bpleager1f@microsoft.com', 'Billie');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Take This Job and Shove It', '2011-09-06', 'pnolder1g@blinklist.com', 'Phaidra');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Russell Peters: Outsourced', '2012-04-16', 'rrobertson1h@multiply.com', 'Rodney');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Season for Miracles, A', '2000-03-31', 'btuddall1i@altervista.org', 'Brina');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Pearl, The (La perla)', '2013-11-19', 'bbroom1j@google.nl', 'Barbette');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Star Is Born, A', '2014-12-01', 'bcallaghan1k@dedecms.com', 'Boonie');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Nanking', '2020-08-13', 'bkolak1l@mozilla.com', 'Bevin');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Trans-Europ-Express', '2008-05-01', 'wfautley1m@nhs.uk', 'Waring');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Color of Pomegranates, The (Sayat Nova)', '2010-01-16', 'mguillard1n@twitpic.com', 'Miguelita');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Fighting Seabees, The', '2011-08-30', 'spurvey1o@51.la', 'Scottie');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Evil That Men Do, The', '2006-05-06', 'kmatushenko1p@telegraph.co.uk', 'Kaleb');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Desert of Forbidden Art, The', '2009-02-04', 'emalyj1q@npr.org', 'Etty');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Citizenfour', '2007-05-08', 'docorhane1r@google.ru', 'Devin');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Kind Hearts and Coronets', '2022-12-03', 'mgealle1s@cocolog-nifty.com', 'Moss');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('13/13/13', '2006-11-02', 'sdederich1t@etsy.com', 'Stanleigh');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Waiting for Forever', '2001-09-12', 'acofax1u@thetimes.co.uk', 'Alexandra');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Balkan Spy (Balkanski spijun)', '2022-09-07', 'awoodham1v@nps.gov', 'Aldon');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Revenge of the Nerds III: The Next Generation', '2010-05-06', 'ccolthurst1w@princeton.edu', 'Chiquia');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Eye of the Dolphin', '2006-09-22', 'ehainey1x@skype.com', 'Erda');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Songcatcher', '2015-09-22', 'tdemer1y@yandex.ru', 'Thorsten');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Ernest Goes to Jail', '2015-12-12', 'rcranfield1z@t-online.de', 'Randell');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Life of Jesus, The (La vie de Jésus)', '2008-05-10', 'msincock20@ihg.com', 'Massimo');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Hysteria: The Def Leppard Story', '2005-11-19', 'briddel21@bluehost.com', 'Birgitta');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('War, Inc.', '2013-10-30', 'gbarmby22@yolasite.com', 'Guy');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('One of Our Aircraft Is Missing', '2006-09-19', 'abrobak23@google.ca', 'Adda');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('License to Drive', '2003-01-30', 'dmurty24@hc360.com', 'De witt');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Police Story (Ging chaat goo si)', '2003-11-06', 'aruilton25@epa.gov', 'Aubrey');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Maelström', '2001-01-26', 'nbickell26@thetimes.co.uk', 'Neel');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Forgive Me', '2013-07-10', 'ssarfatti27@hibu.com', 'Shelley');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Father''s Little Dividend', '2011-08-26', 'bgadd28@reverbnation.com', 'Bertram');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Igby Goes Down', '2019-12-02', 'lmanhare29@1und1.de', 'Lyn');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Nobody', '2007-02-06', 'ekuhlmey2a@surveymonkey.com', 'Elfreda');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Love & Pop', '2023-08-17', 'rmalecky2b@nba.com', 'Rudyard');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Shock to the System, A', '2012-08-24', 'jrugiero2c@jalbum.net', 'Joanna');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Death Wish 3', '2010-08-23', 'kgrayling2d@usnews.com', 'Kele');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Hunter, The', '2006-04-05', 'crigler2e@bing.com', 'Christye');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Court-Martial of Billy Mitchell, The', '2002-10-31', 'kroscam2f@hubpages.com', 'Kristel');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Addams Family Values', '2002-02-18', 'urobardley2g@skype.com', 'Ursola');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('How She Move', '2000-04-22', 'rarnoult2h@senate.gov', 'Rachel');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Freddy Got Fingered', '2021-11-26', 'bpetruszka2i@blogs.com', 'Bald');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Dust in the Wind (Lian lian feng chen)', '2016-10-03', 'feastment2j@over-blog.com', 'Faye');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Maxed Out: Hard Times, Easy Credit and the Era of Predatory Lenders', '2002-01-27', 'dmattheissen2k@soundcloud.com', 'Dominique');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Affinity', '2022-06-10', 'mkollach2l@studiopress.com', 'Marget');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Tale of Zatoichi, The (Zatôichi monogatari) (Zatôichi 1)', '2000-11-11', 'emongan2m@cbslocal.com', 'Erskine');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Tables Turned on the Gardener', '2000-04-15', 'emacpaden2n@google.pl', 'Elie');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Child Bride', '2008-02-19', 'bburkinshaw2o@blogtalkradio.com', 'Beck');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Left Behind', '2001-05-22', 'bpetyanin2p@cmu.edu', 'Bernadina');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Brand Upon the Brain!', '2021-10-13', 'jbartholin2q@bloomberg.com', 'Josee');
insert into Movies (Title, ReleaseDate, Genres, Director) values ('Greatest Movie Ever Sold, The (POM Wonderful Presents: The Greatest Movie Ever Sold)', '2001-03-04', 'amarchington2r@ed.gov', 'Adan');
